version: '3'

vars:
  DOCKER_FOLDERS:
    sh: ls -d */
  DOCKER_GID:
    sh: "getent group docker | cut -d: -f3"
  ENV_FILE: "{{ .ROOT_DIR }}/.env"

env:
  DOCKER_GID: '{{.DOCKER_GID}}'

tasks:
  start-or-update:
    aliases:
    - start
    - update
    desc: Start or update doco-cd stack to deploy repository
    cmds:
    - docker compose --env-file {{.ENV_FILE}} up --detach --remove-orphans
    silent: true
  cleanup:
    desc: Delete unused docker images
    cmds:
      - docker image prune -a -f
  