version: '3'

vars:
  DOCKER_FOLDERS:
    sh: ls -d */
  DOCKER_GID:
    sh: "getent group docker | cut -d: -f3"
  ENV_FILE: "{{ .ROOT_DIR }}/.env"

env:
  DOCKER_GID: '{{.DOCKER_GID}}'

tasks:
  all-destroy:
    aliases:
    - destroy-all
    desc: Run docker compose down on all stacks, including volumes
    cmds:
    - for: { var: DOCKER_FOLDERS }
      cmd: docker compose --env-file {{.ENV_FILE}} -f {{.ITEM}}/docker-compose.yml down --volumes
  
  all-down:
    aliases:
    - down-all
    desc: Run docker compose down on all stacks, excluding volumes
    cmds:
    - for: { var: DOCKER_FOLDERS }
      cmd: docker compose --env-file {{.ENV_FILE}} -f {{.ITEM}}/docker-compose.yml down

  all-up:
    aliases:
    - up-all
    desc: Run docker compose up on all stacks
    cmds:
    - for: { var: DOCKER_FOLDERS }
      cmd: docker compose --env-file {{.ENV_FILE}} -f {{.ITEM}}/docker-compose.yml up --build -d --remove-orphans

  cleanup:
    desc: Delete unused docker images
    cmds:
      - docker image prune -a -f
      
  destroy:
    desc: Destroy stack in current folder, including volumes
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - test -f docker-compose.yml
    cmds:
      - docker compose --env-file {{.ENV_FILE}} down --volumes
  
  down:
    desc: Destroy stack in current folder, excluding volumes
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - test -f docker-compose.yml
    cmds:
      - docker compose --env-file {{.ENV_FILE}} down
  
  hello:
    desc: Hello world task
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  up:
    desc: Deploy stack in current folder
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - test -f docker-compose.yml
    cmds:
      - docker compose --env-file {{.ENV_FILE}} up --build -d --remove-orphans