services:
  mongodb:
    container_name: mongodb
    image: mongo:6.0.19
    networks:
    - graylog
    volumes:
    - mongodb_data:/data/db
    restart: unless-stopped
  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:2.18.0
    environment:
    - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
    - bootstrap.memory_lock=true
    - discovery.type=single-node
    - action.auto_create_index=false
    - plugins.security.ssl.http.enabled=false
    - plugins.security.disabled=true
    - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${GRAYLOG_OPENSEARCH}
    networks:
    - graylog
    restart: unless-stopped
  graylog:
    container_name: graylog
    image: graylog/graylog:6.1
    depends_on:
      mongodb:
        condition: service_started
      opensearch:
        condition: service_started
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 -- /docker-entrypoint.sh
    environment:
    - GRAYLOG_NODE_ID_FILE=/usr/share/graylog/data/config/node-id
    - GRAYLOG_HTTP_BIND_ADDRESS=0.0.0.0:9000
    - GRAYLOG_ELASTICSEARCH_HOSTS=http://opensearch:9200
    - GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog
    - GRAYLOG_REPORT_DISABLE_SANDBOX=true
    - GRAYLOG_PASSWORD_SECRET=${GRAYLOG_SECRET}
    - GRAYLOG_ROOT_PASSWORD_SHA2=${GRAYLOG_ADMIN_HASH}
    - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    ports:
    - 9000:9000/tcp
    - 5044:5044/tcp
    - 5140:5140/tcp
    - 5140:5140/udp
    - 12201:12201/tcp
    - 13301:13301/tcp
    - 13302:13302/tcp
    networks:
    - graylog
    volumes:
    - graylog_data:/usr/share/graylog/data/data
    - graylog_journal:/usr/share/graylog/data/journal
    restart: unless-stopped
networks:
  graylog:
    driver: bridge

volumes:
  mongodb_data:
  graylog_data:
  graylog_journal:
